# This is the Jekyll configuration file (https://jekyllrb.com/docs/configuration/)

# Default theme is primer (see https://github.com/pages-themes/primer)

# Title to display at the top of all pages
# If you don't want a title, it is necessary to set it to null because the 
# github-metadata plugin (see https://github.com/jekyll/github-metadata#what-it-does)
# sets it to the repo name by default.
title: "To01z test"
